Multiwoven/multiwoven-ui

src/chakra.config.ts, src/components/EntityItem/EntityItem.tsx, src/views/Connectors/Sources/SourcesForm/SourceConfigForm/SourceConfigForm.tsx, src/views/Sidebar/Profile.tsx, src/views/Sidebar/navButton.tsx
Fixed some alignment issues and changed popover items to button from box
=> Merge Fix/profile UI into Develop

src/routes/index.tsx, src/views/Connectors/Sources/SourcesForm/SelectDataSourcesForm/SelectDataSourcesForm.tsx
- Fixed routing error when signing in
- removed unused imports and hook to fix build error
=> Minor Fixes

src/views/Authentication/SignIn/SignIn.tsx, src/views/Authentication/SignUp/SignUp.tsx
Fixed the label and error message sizes. Also changed the color for placeholder text and input text
=> Fixed error message colors and label sizes

src/components/EntityItem/EntityItem.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx, src/views/Activate/Syncs/SyncForm/FinaliseSync/FinaliseSync.tsx, src/views/Activate/Syncs/SyncForm/SelectDestination/SelectDestination.tsx, src/views/Connectors/Sources/SourcesForm/SourceFormFooter/SourceFormFooter.tsx
Added conditionally rendering of footer elements while creating syncs.
At some steps, we do not need `Read Documentation` Links
=> fix: conditionally render footer elements in create sync

src/components/Table/Table.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/MapFields.tsx, src/views/Models/ModelsForm/FinalizeModel/FinalizeModel.tsx, src/views/Models/ViewModel/DeleteModelModal/DeleteModelModal.tsx
Fixed the bug to persist multiple mappings while navigating back and forth in multiple steps
https://github.com/Multiwoven/multiwoven-ui/assets/29303618/1d2aa867-f0d3-4240-b320-cd6e30798c4d
=> fix: multiple mapping bug during create sync

src/components/Table/Table.tsx, src/views/Activate/Syncs/EditSync/EditSync.tsx, src/views/Activate/Syncs/EditSync/ScheduleForm.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/FieldMap.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/MapFields.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/SelectStreams.tsx, src/views/Activate/Syncs/SyncForm/FinaliseSync/FinaliseSync.tsx
Updated the UI designs as per review feedback
=> style: Syncs UI feedback

src/views/Connectors/Destinations/DestinationsForm/DestinationConfigForm/DestinationConfigForm.tsx, src/views/Connectors/Destinations/DestinationsForm/DestinationConnectionTest/DestinationConnectionTest.tsx, src/views/Connectors/Destinations/DestinationsForm/DestinationFinalizeForm/DestinationFinalizeForm.tsx, src/views/Connectors/Destinations/DestinationsForm/DestinationsForm.tsx, src/views/Connectors/Destinations/DestinationsForm/SelectDestinations/SelectDestinations.tsx, src/views/Connectors/NoConnectors/NoConnectors.tsx, src/views/Connectors/Sources/SourcesForm/SourceConfigForm/SourceConfigForm.tsx, src/views/Connectors/Sources/rjsf/BaseInputTemplate.tsx, src/views/Connectors/Sources/rjsf/TitleFieldTemplate.tsx, src/views/MainLayout/MainLayout.tsx
Destination UI screen as per Figma designs
=> style: destinations screen

src/chakra.config.ts, src/views/Authentication/SignIn/SignIn.tsx, src/views/Authentication/SignUp/SignUp.tsx
Fixed the issue where a hovered button when loading would be invisible
Also fixed the issue when you login for the first time, it takes you to a blank screen.
=> Fixed Button Hovering and Auth Login routing issue

src/services/connectors.ts, src/views/Connectors/Destinations/DestinationsForm/DestinationConnectionTest/DestinationConnectionTest.tsx, src/views/Connectors/Sources/EditSource/EditSource.tsx, src/views/Connectors/Sources/EditSource/SourceActions.tsx, src/views/Connectors/Sources/SourcesForm/SelectDataSourcesForm/SelectDataSourcesForm.tsx, src/views/Connectors/Sources/SourcesForm/SourceConfigForm/SourceConfigForm.tsx, src/views/Connectors/Sources/SourcesForm/SourceConnectionTest/SourceConnectionTest.tsx, src/views/Connectors/Sources/SourcesForm/SourceFinalizeForm/SourceFinalizeForm.tsx, src/views/Connectors/Sources/SourcesForm/SourceFormFooter/SourceFormFooter.tsx, src/views/Connectors/Sources/SourcesList/SourcesList.tsx, src/views/Connectors/Sources/rjsf/BaseInputTemplate.tsx
Updated the sources screen to match as per the Figma designs.
> Edit source screen
> List source screen
=> style: sources ui

server-config/nginx.conf
Changed Nginx listening port from 8080 to 8000
=> Changed Nginx Port from 8080 to 8000

.github/ISSUE_TEMPLATE/bug_report_template.md, .github/ISSUE_TEMPLATE/documentation_update_template.md, .github/ISSUE_TEMPLATE/feature_request_template.md
Added the template to create issues for the following types
- Report a bug
- Suggest changes in documentation
- Raise a feature request
=> feat: add issue templates

src/views/Connectors/Sources/SourcesForm/SourceFormFooter/SourceFormFooter.tsx
Updated the contact support to point to the slack public channel
=> fix: update contact support to point to slack

src/views/Authentication/SignIn/SignIn.tsx, src/views/Sidebar/Profile.tsx
After successful sign-in, the users were seeing a white screen and the content was loading after a page refresh. Fixed this issue.
=> fix: blank screen after success sign in

.github/workflows/validate.yml
Added github action to:
- build source code
- lint source code
=> feat: github actions to validate source code

src/views/Dashboard/Dashboard.tsx, src/views/Dashboard/ListConnectors.tsx
Added the functionality to the connectors list to filter by source and destination
https://github.com/Multiwoven/multiwoven-ui/assets/29303618/e48987c0-79cd-44d0-8959-a257f654d45f
=> feat: filter connectors list

src/views/Dashboard/ListConnectors.tsx, src/views/Dashboard/Pagination.tsx
Added pagination to the list of connectors we are showing
=> feat: paginate connectors list

src/services/dashboard.ts, src/views/Dashboard/Dashboard.tsx, src/views/Dashboard/ListConnectors.tsx, src/views/Dashboard/Reports/ChartCard.tsx, src/views/Dashboard/Reports/Reports.tsx
Fetch reports during checking and unchecking connectors
https://github.com/Multiwoven/multiwoven-ui/issues/99
https://github.com/Multiwoven/multiwoven-ui/assets/29303618/fd19bc29-8156-485d-8ce0-b7711e79df69
=> feat: fetch reports on connectors check

src/routes/index.tsx, src/views/Authentication/SignIn/SignIn.tsx, src/views/Authentication/SignUp/SignUp.tsx
Updated the redirect route to point to dashboard
=> fix: update redirect route for dashboard

__mocks__/moment.js, src/components/StatusTag/StatusTag.tsx, src/components/TabItem/TabItem.tsx, src/components/TabItem/index.ts, src/services/syncs.ts, src/views/Activate/SetupActivate/SetupActivate.tsx, src/views/Activate/Syncs/EditSync/EditSync.tsx, src/views/Activate/Syncs/SyncRuns/ResultEntity.tsx, src/views/Activate/Syncs/SyncRuns/SyncRunTableItem.tsx, src/views/Activate/Syncs/SyncRuns/SyncRuns.tsx, src/views/Activate/Syncs/SyncRuns/index.ts, src/views/Activate/Syncs/ViewSync/ViewSync.tsx, src/views/Activate/Syncs/ViewSync/index.ts, src/views/Activate/Syncs/__tests__/SyncRunsTableItem.test.tsx, src/views/Activate/Syncs/constants.ts, src/views/Activate/Syncs/types.ts, src/views/Connectors/types.ts
Added Sync Runs to the View Sync screen with toggle for Sync Runs and Configuration
`npm run test` output
Sync Runs (first is healthy and second is in progress but we are keeping as failed for now as design is not ready for it yet):
Added Unit Tests to verify if Table Item is rendering the correct data
=> [FEATURE] added sync runs

src/components/Toast/index.tsx
Update the styling of the toast component to use the correct tokens
https://github.com/Multiwoven/multiwoven-ui/issues/77
=> style: update styling for custom toast component

Dockerfile.dev
=> fix: update docker dev with env

.github/workflows/docker-build.yml, Dockerfile, package.json
=> Modifed the Dockerfile to pickup ENV in runtime for VITE_API_HOST

src/views/Activate/Syncs/EditSync/EditSync.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/SelectStreams.tsx, src/views/Activate/Syncs/types.ts
Displaying sync modes during sync creation
=> feat: sync modes

src/chakra.config.ts, src/views/Authentication/SignIn/SignIn.tsx, src/views/Authentication/SignIn/__tests__/signin.test.tsx, src/views/Authentication/SignUp/SignUp.tsx, src/views/Authentication/SignUp/__tests__/signup.test.tsx, src/views/Sidebar/Sidebar.tsx
Added support for enterprise edition
https://github.com/Multiwoven/multiwoven-ui/assets/29303618/b6403980-3396-4915-b1df-4f38994ab250
=> feat: introducing enterprise edition

Dockerfile, package.json
=> docker production run issue

src/views/Activate/Syncs/EditSync/EditSync.tsx, src/views/Activate/Syncs/SyncForm/ConfigureSyncs/ConfigureSyncs.tsx
Added sync modes for Full Refresh and Refactor to Schemaless Sync
[Screencast from 2024-03-27 19-42-43.webm](https://github.com/Multiwoven/multiwoven-ui/assets/54372016/719dee97-2c82-419d-872f-cf8d1df9dc77)
=> refactor: fixed stream and sync mode selector

Dockerfile
=> Update Dockerfile to remove api host key
